{
 "title": "Sentences dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sentence_requests_total{namespace=\"$namespace\"}[3m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "POD count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sentence_requests_total{namespace=\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "POD CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"sentence-age.*\", image!=\"\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "age"
    },
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"sentence-name.*\", image!=\"\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "name"
    },
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"sentences.*\", image!=\"\", namespace=\"$namespace\"}[3m]))",
     "legendFormat": "sentence"
    }
   ]
  }
 ]
}