# The base image
FROM ubuntu:latest

# Install python and pip
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

# Install Python modules needed by the Python app
COPY test_requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/test_requirements.txt

# Copy tests
COPY tests/*.py /usr/src/app/tests/
COPY unit_tests/*.py /usr/src/app/unit_tests/

# Run the application
ENTRYPOINT ["python"]
CMD ["/usr/src/app/tests/test_service.py"]
