apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: probing
spec:
  containers:
  - name: liveness
    image: gcr.io/google_containers/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; touch /tmp/ready; echo "ready"; sleep 6000
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 15
      failureThreshold: 1
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 2