apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-guaranteed
  name: nginx-guaranteed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-guaranteed
  template:
    metadata:
      labels:
        app: nginx-guaranteed
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 0.25
          requests:
            cpu: 0.25
