rbac:
  create: false
serviceAccounts:
  server:
    create: false
    name: prometheus-server
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
networkPolicy:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
server:
  retention: '1d'
  resources:
    limits:
      cpu: 250m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    type: NodePort